### ISSUE TITLE
求教，按教程来的但没法复现，train和interface都出现了同样的问题

### ISSUE THREAD

**Issue by PaiDaxing114514** [megvii-research/MOTRv2#58]
train的output.log
Start training
Traceback (most recent call last):
  File "main.py", line 332, in <module>
    main(args)
  File "main.py", line 305, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm)
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\engine.py", line 39, in train_one_epoch_mot
    for data_dict in metric_logger.log_every(data_loader, print_freq, header):
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\util\misc.py", line 229, in log_every
    for obj in iterable:
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\datasets\dance.py", line 224, in __getitem__
    images, targets = self.pre_continuous_frames(vid, indices)
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\datasets\dance.py", line 211, in pre_continuous_frames
    return zip(*[self._pre_single_frame(vid, i) for i in indices])
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\datasets\dance.py", line 211, in <listcomp>
    return zip(*[self._pre_single_frame(vid, i) for i in indices])
  File "E:\ZCH\MOTRv2-main\exps\motrv2\run3\datasets\dance.py", line 186, in _pre_single_frame
    for line in self.det_db[txt_key]:
KeyError: 'DanceTrack/train\\dancetrack0016\\img1\\00001220.txt'
Traceback (most recent call last):
  File "D:\Anaconda\envs\motrv2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\motrv2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\distributed\launch.py", line 340, in <module>
    main()
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\distributed\launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\distributed\launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Anaconda\\envs\\motrv2\\python.exe', '-u', 'main.py', '--meta_arch', 'motr', '--dataset_file', 'e2e_dance', '--epoch', '5', '--with_box_refine', '--lr_drop', '4', '--lr', '2e-4', '--lr_backbone', '2e-5', '--pretrained', 'E:/ZCH/MOTRv2-main/data/Dataset/DanceTrack/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth', '--batch_size', '1', '--sample_mode', 'random_interval', '--sample_interval', '10', '--sampler_lengths', '5', '--merger_dropout', '0', '--dropout', '0', '--random_drop', '0.1', '--fp_ratio', '0.3', '--query_interaction_layer', 'QIMv2', '--query_denoise', '0.05', '--num_queries', '10', '--append_crowd', '--det_db', 'det_db_motrv2.json', '--use_checkpoint', '--output_dir', '.']' returned non-zero exit status 1.
Killing subprocess 17460

**Comment by PaiDaxing114514** [comment]
Why do we get keyerror

**Comment by PaiDaxing114514** [comment]
interface Keyerror：
Training with Self-Cross Attention.
loaded ./motrv2_dancetrack.pth
  0%|          | 0/1203 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "submit_dance.py", line 211, in <module>
    det.detect(args.score_threshold)
  File "submit_dance.py", line 118, in detect
    for i, data in enumerate(tqdm(loader)):
  File "D:\Anaconda\envs\motrv2\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\motrv2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "submit_dance.py", line 76, in __getitem__
    img, proposals = self.load_img_from_file(self.img_list[index])
  File "submit_dance.py", line 50, in load_img_from_file
    for line in self.det_db[f_path[:-4] + '.txt']:
KeyError: 'DanceTrack/test\\dancetrack0003\\img1\\00000001.txt'

**Comment by dcstempt** [comment]
the right key is "'DanceTrack\test\dancetrack0003\img1\00000001.txt'",
not                    "'DanceTrack/test\dancetrack0003\img1\00000001.txt'".
It is "\", not "/"

**Comment by dcstempt** [comment]
the right key is "'DanceTrack\test\dancetrack0003\img1\00000001.txt'",
not "'DanceTrack/test\dancetrack0003\img1\00000001.txt'".
It is "\", not "/"

**Comment by dcstempt** [comment]
the right key is "'DanceTrack\test\dancetrack0003\img1\00000001.txt'",
not "'DanceTrack/test\dancetrack0003\img1\00000001.txt'".
Do not use "/"
